### ISSUE TITLE
declaration of beforeSave seems to be incompatible with the default translatebehavior.

### ISSUE THREAD

**Issue by danielzzz** [AD7six/cakephp-shadow-translate#17]
Hi, I'm getting this error:

Strict (2048): Declaration of ShadowTranslate\Model\Behavior\ShadowTranslateBehavior::beforeSave() should be compatible with Cake\ORM\Behavior\TranslateBehavior::beforeSave(Cake\Event\Event $event, Cake\Datasource\EntityInterface $entity, ArrayObject $options) [ROOT/vendor/ad7six/shadow-translate/src/Model/Behavior/ShadowTranslateBehavior.php, line 19]

but I checked and the both functions seems to have the same parameters..
I've been looking around but not sure how to fix it.

best, dan

**Comment by danielzzz** [comment]
not sure if it matters, but I'm using cake 3.0.10 atm and shadow-translate:dev-master

**Comment by ADmad** [comment]
It's [this](https://github.com/cakephp/cakephp/pull/6926/files#diff-f6187e37f58ec2b930e9e51932c8a85bR255) change that is causing the error.

**Comment by ADmad** [comment]
Fixed in #18.

@AD7six Could you please make a new release.
