### ISSUE TITLE
translations are not being saved

### ISSUE THREAD

**Issue by danielzzz** [AD7six/cakephp-shadow-translate#19]
hi, sorry to bother, but suddenly it seems that translations stopped being saved and I cannot figure why... 

I have use TranslateTrait; in my entity and 

    $this->addBehavior('ShadowTranslate.ShadowTranslate'); in my table class.

I have two languages es_ES and es_CA.
my request data is:

```
[
	'active' => '1',
	'box_type_id' => '229cf0c1-a20f-4991-9d00-f3fd1c60d824',
	'item_order' => '2',
	'icon' => 'fa-area-chart',
	'es_CA' => [
		'title' => 'asdasd',
		'description' => 'asdas',
		'link_title' => ''
	],
	'title' => 'sdfasdfasdf',
	'description' => 'assdfa',
	'link_title' => 'sadfsd',
	'link' => 'http://google.es'
]
```
and I am pretty sure I always used in controller (o maybe I just dreamt it :/)

    $homeBox = $this->HomeBoxes->get($id, ['contain' => []]);
    $homeBox = $this->HomeBoxes->patchEntity($homeBox, $this->request->data);
    $this->HomeBoxes->save($homeBox);
 
(I have some old records in my home_boxes_translations table).
but then nothing is saved there. just the main table is being updated.
this is happening across the whole app and I am a bit puzzled what may cause this...
any help would be appreciated, thanks!

**Comment by AD7six** [comment]
```
[
    ...
    'es_CA' => [
        'title' => 'asdasd',
        'description' => 'asdas',
        'link_title' => ''
    ],
    ...
]
```

This data structure isn't something I'm familiar with - it'll just be ignored. Are you trying to save in two languages at the same time? If so your code does not match [the example in the docs](http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-multiple-translations) - there's no call to `$entity->translation($lang)`

**Comment by AD7six** [comment]
Closing due to lack of feedback

**Comment by danielzzz** [comment]
sorry. I was traveling. yes I am trying to save all languages at the same time. I've seen it was not possible... will try another approach. thanks!

**Comment by danielzzz** [comment]
sorry, still having problems with this...

I set now all the translation data using $entity->translation($lang) and it seems to be set correctly, but I get the following error when trying to save:
Cannot insert row, some of the primary key values are missing. Got (6112de76-32d9-4fed-955c-64766813af54, ), expecting (id, locale)

this is my entity after patching and before save. you can see it has es_CA data set (the default is es_ES)
object(App\Model\Entity\HomeBanner) {

	'id' => '6112de76-32d9-4fed-955c-64766813af54',
	'title' => 'default title',
	'description' => 'some description',
	'link' => '/test1',
	'_translations' => [
		'es_CA' => object(App\Model\Entity\HomeBanner) {

			'title' => 'asdasda',
			'description' => 'sasdasd asdasdasdas',
			'[new]' => true,
			'[accessible]' => [
				'active' => true,
				'item_order' => true,
				'image' => true,
				'image_dir' => true,
				'title' => true,
				'description' => true,
				'link' => true
			],
			'[dirty]' => [
				'title' => true,
				'description' => true
			],
			'[original]' => [],
			'[virtual]' => [],
			'[errors]' => [],
			'[repository]' => null
		
		}
	],
	'[new]' => false,
	'[accessible]' => [
		'active' => true,
		'item_order' => true,
		'image' => true,
		'image_dir' => true,
		'title' => true,
		'description' => true,
		'link' => true
	],
	'[dirty]' => [
		'active' => true,
		'item_order' => true,
		'title' => true,
		'description' => true,
		'link' => true,
		'image' => true,
		'_translations' => true
	],
	'[original]' => [
		'active' => true,
		'item_order' => (int) 1,
		'image' => 'foto_01.jpg',
		'_translations' => []
	],
	'[virtual]' => [],
	'[errors]' => [],
	'[repository]' => 'HomeBanners'

}

**Comment by danielzzz** [comment]
I solved this, by setting the locale field manually for translations, but I feel this should be set automatically when using $entity->translation($lang)

**Comment by AD7six** [comment]
Ok, I'll see if I can reproduce that.

**Comment by AD7six** [comment]
I can't reproduce any kind of problem.

[Here are the test files I used](https://gist.github.com/AD7six/c17ea65a78cb06d607b2), here's the test method/setup:

```
-> git diff
diff --git tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php
index e7a299d..909b22a 100644
--- tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php
+++ tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php
@@ -1,6 +1,7 @@
 <?php
 namespace ShadowTranslate\Test\TestCase\Model\Behavior;
 
+use Cake\Datasource\ConnectionManager;
 use Cake\ORM\TableRegistry;
 use Cake\TestSuite\TestCase;
 use Cake\Test\TestCase\ORM\Behavior\TranslateBehaviorTest;
@@ -19,6 +20,8 @@ class ShadowTranslateBehaviorTest extends TranslateBehaviorTest
         'plugin.ShadowTranslate.ArticlesMoreTranslations',
         'plugin.ShadowTranslate.AuthorsTranslations',
         'plugin.ShadowTranslate.CommentsTranslations',
+        'plugin.ShadowTranslate.HomeBoxes',
+        'plugin.ShadowTranslate.HomeBoxesTranslations',
     ];
 
     /**
@@ -38,6 +41,48 @@ class ShadowTranslateBehaviorTest extends TranslateBehaviorTest
         parent::setUp();
     }
 
+    public function testIssue19()
+    {
+        $table = TableRegistry::get(
+            'HomeBoxes',
+            [
+                'className' => 'ShadowTranslate\Test\TestCase\Model\Behavior\HomeBoxesTable'
+            ]
+        );
+
+        $table->addBehavior(
+            'ShadowTranslate.ShadowTranslate',
+            [
+                'defaultLocale' => 'es_ES'
+            ]
+        );
+        $table->locale('es_ES');
+
+        $entity = $table->newEntity();
+        $entity->title = 'ooo bueno';
+        $table->save($entity);
+
+        $entity->translation('es_CA')->title = 'che q bo';
+        $table->save($entity);
+
+        $saved = $table->find()->first();
+        $this->assertSame('ooo bueno', $saved->title);
+
+        $table->locale('es_CA');
+        $saved = $table->find()->first();
+        $this->assertSame('che q bo', $saved->title);
+
+        $saved->translation('es_CA')->title = 'res de bo';
+        $table->save($saved);
+
+        $connection = ConnectionManager::get('default');
+        $results = $connection->execute('SELECT * FROM home_boxes')->fetchAll('assoc');
+        debug($results);
+
+        $results = $connection->execute('SELECT * FROM home_boxes_translations')->fetchAll('assoc');
+        debug($results);
+    }
+
     /**
      * Make sure the test Table class addBehavior method works
      *
```

And this is the result:

```
www-data @ dev [ /home/andy/repos/AD7six/cakephp-shadow-translate ] (master *$%=)
-> phpunit --filter testIssue19  tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php
PHPUnit 4.4.1 by Sebastian Bergmann.

Configuration read from /home/andy/repos/AD7six/cakephp-shadow-translate/phpunit.xml

./home/andy/repos/AD7six/cakephp-shadow-translate/tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php (line 82)
########## DEBUG ##########
[
	(int) 0 => [
		'id' => '5fde9047-4445-410a-b7fb-f9f3a8408439',
		'active' => null,
		'box_type_id' => null,
		'icon' => null,
		'title' => 'ooo bueno',
		'description' => null,
		'link_title' => null,
		'link' => null
	]
]
###########################
/home/andy/repos/AD7six/cakephp-shadow-translate/tests/TestCase/Model/Behavior/ShadowTranslateBehaviorTest.php (line 85)
########## DEBUG ##########
[
	(int) 0 => [
		'id' => '5fde9047-4445-410a-b7fb-f9f3a8408439',
		'locale' => 'es_CA',
		'title' => 'res de bo',
		'description' => null,
		'link_title' => null
	]
]
###########################


Time: 236 ms, Memory: 12.25Mb

OK (1 test, 2 assertions)
```

If it's still not working for you, you'll need to provide your actual code and reproduction steps for me to be able to help you.

**Comment by AD7six** [comment]
So it transpires that this is a "duplicate" of #20, the local doesn't get set because the locale field isn't in the accessible property list; the test cases rely on no accessibile property being defined.

**Comment by danielzzz** [comment]
It's weird, right now I cannot reproduce this error either... :/
first I added "locale" to the "accessible" array and it worked. but then when I commented it out, it still works... so at the end I am not sure what caused the error. sorry...
