### ISSUE TITLE
you have to add locale in the entity manually atm

### ISSUE THREAD

**Issue by mrnnn** [AD7six/cakephp-shadow-translate#20]
Hi hi,

I had some troubles getting things going and noticed it all started working as soon as I added 'locale' to the $_accessible array of the enity. Works fine for me, but worth mentioning I think :-)

**Comment by AD7six** [comment]
Some info would be helpful, what method call with model file definition didn't work? 

The title of the ticket is not accurate afaik, see the test cases.

**Comment by AD7six** [comment]
Bump

**Comment by mrnnn** [comment]
Hey Andy.

Basically, the 'locale' attribute of the entity was not accessible. As a consequence, saving in another language as described in the cookbook ( http://book.cakephp.org/3.0/en/orm/behaviors/translate.html#saving-in-another-language) did not work.

I have to say that since, we have just forked the plugin to adapt our preferred behaviour (being: we have not default language which is later translated. any language can be the default. An 'add' operation will create de default and add the translation. Additionally, a delete will only delete the translation. So maybe I was expecting things this plugin was not really meant to do :-).

Either way, performance is great. So a thank you is in place :-)

**Comment by AD7six** [comment]
Ok I understand the locale problem - and will get that fixed.

I don't understand the rest of what you've written - but I recommend you don't create a new behavior for that, it sounds like configuration or not-translate-behavior-related rather than something else.
