### ISSUE TITLE
Script for migrating from core translate behaviour to ShadowTranslate

### ISSUE THREAD

**Issue by Spriz** [AD7six/cakephp-shadow-translate#24]
Hi!

I just made a cake shell for doing the migration of i18n table content from core behaviour - anything I should prettify and make a PR with - or is it outside the scope?

**Comment by AD7six** [comment]
That's [in scope](https://github.com/AD7six/cakephp-shadow-translate#roadmap) =)

**Comment by Spriz** [comment]
Made #26
