### ISSUE TITLE
Can't use the behavior in a ORM standalone installation

### ISSUE THREAD

**Issue by burzum** [AD7six/cakephp-shadow-translate#27]
The plugin requires CakePHP 3, in fact I think it should only require the ORM but not CakePHP3 because the ORM can be used alone. That's what we do here, using the new ORM in a Cake2 app to migrate it as we go to the new ORM. But the dependency settings avoid the use of this plugin together with just the ORM.

**Comment by AD7six** [comment]
Closed by https://github.com/AD7six/cakephp-shadow-translate/pull/30

Thanks @burzum !
