### ISSUE TITLE
Using the behavior in a shell (loop) will fill the memory

### ISSUE THREAD

**Issue by burzum** [AD7six/cakephp-shadow-translate#31]
The behaviors seems to have a memory problem somewhere. im using it as it is in a shell to build my elastic index, when i remove the translate behavior from the model i import the memory doesn't grow. As soon as I attach it it becomes more and more over time.

The problems seems to be coming from the row mapper. If I add a `return` before 

```php
        $query->formatResults(function ($results) use ($locale) {
            return $this->_rowMapper($results, $locale);
        }, $query::PREPEND);
```

The memory stops from going up. The same applies to the core behavior. Your's is overloading the `beforeFind` and `_rowMapper` methods completely. So I think the issue is in the way the rowMapper is implemented. I'm using php 5.6 on windows. I *guess* the issue is somehow related to the closures, *guess* the functions get over and over created in memory or something like this.

**Comment by ADmad** [comment]
The issue is in CakePHP core (in PHP itself to be precise). So whatever the fix will be done in core.
