### ISSUE TITLE
Disabling using a default language

### ISSUE THREAD

**Issue by greew** [AD7six/cakephp-shadow-translate#35]
Hi

My use case is as follows:

We're creating a site using English (en_GB) as only language, but the site is used to create content for other sites in various languages. The content we're creating doesn't have a default language, meaning you don't have to create the content in English first and then translate it. You "just" create it in your own language. When a person has created new content in eg. Danish, another person can translate this content into Norwegian, without the need to ever translate it into English.

That above use case means, that I can't use the ShadowTranslateBehavior as is, because with this I need to always create an English version first and then translate it afterwards.

I have, however, made a change to the ShadowTranslateBehavior that enables me to do this, and I'm curious if this in any way is interesting for this repository?

This is partly discussed in #23, but this is not a bug but rather a feature request or a "feature offer" :)

**Comment by ADmad** [comment]
I am interested in seeing your feature implementation :)

**Comment by greew** [comment]
@ADmad Check out greew/cakephp-shadow-translate@28de2f3e05e8c80c0b942a501b1071919942eca4

**Comment by ADmad** [comment]
Can't what you want be achieved by setting `defaultLocale` in behavior config to a non-existent locale?

**Comment by AD7six** [comment]
> Can't what you want be achieved by setting defaultLocale in behavior config to a non-existent locale?

Is it not viable in your situation to set defaultLocale to the locale of the request?

**Comment by AD7six** [comment]
scratch that - a fictitious default local such as `xx` is what I'd do in that scenario

**Comment by AD7six** [comment]
I looked over the linked code - please let me know if setting the default locale to something bogus does not solve your problem, it looks to me like it would.

**Comment by greew** [comment]
Yeah, I'm testing it right now - I'll let you know, as soon as I have an answer.
Thanks for looking into the code!

**Comment by greew** [comment]
I won't be working on this anymore, so I'll just close this for now :)
