### ISSUE TITLE
RFC: Turn array keys of the the _i18n property into locales

### ISSUE THREAD

**Issue by burzum** [AD7six/cakephp-shadow-translate#40]
Reason: I need to auto generate fields based on available languages for a specific client, it doesn't matter if the translation is already present or not. So the most easy solution would be to work with the _i18n assoc and saving these assocs. But to get the right ones in the views is not easy. This small change would it make a lot more easy to address a specific translation in a view:

``` php
            $tmp = [];
            foreach ($row->_i18n as $key => $translation) {
                $tmp[$translation['locale']] = $translation;
            }
            $row->_i18n = $tmp;
```

In the view you can simply do something like this:

``` php
foreach ($locales as $locale) {
    echo $this->Form->input('_i18n.' . $locale . '.foo');
    echo $this->Form->input('_i18n.' . $locale . '.bar');
}
```

I'm using a helper for that task but you get the idea I think.

In the case you think this is bloat it could be made an optional feature, by default set to off.

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
