### ISSUE TITLE
Doesn't work when using method translationField() for translatable fields

### ISSUE THREAD

**Issue by berarma** [AD7six/cakephp-shadow-translate#51]
When using ```translationField()``` as explained in https://book.cakephp.org/3.0/en/orm/behaviors/translate.html#querying-translated-fields translation tables aren't queried and the query fails. The same happens when using the model alias.

It just works when not specifying alias at all. It makes it harder to switch from/to the original behavior.

**Comment by ADmad** [comment]
`translationField()` method just adds the the shadowtable's model alias as prefix to field name nothing more.

You need to provide more details about your actual find call and generated query.

**Comment by ADmad** [comment]
@berarma Can this be closed? I believe the actual problem is the one you stated in next issue.

**Comment by berarma** [comment]
Probably. I wasn't able to reproduce the problem but I thought it would happen again. It didn't happen so closing. Thanks.
