### ISSUE TITLE
Tweaking to use registry alias / some bugs

### ISSUE THREAD

**Issue by patrickconroy** [AD7six/cakephp-shadow-translate#8]
Hi @AD7six, I'm starting to use this plugin to see how much more performant it can be with my app (nothing's not translated). I made a commit @ https://github.com/patrickconroy/cakephp-shadow-translate/commit/2e0b133ab1da8b3076c5ca7e2db08d2f0720a487 that attempts to fix how the translation table is set/get in the registry, which was updated in the 3.0 core. Right now my commit almost works, but there are some issues..

```
# VideosTable
$this->addBehavior('ShadowTranslate.ShadowTranslate', [
	'translationTable' => 'VideosTranslations',
	'fields' => ['title', 'description'']
]);
$this->addAssociations([
	'belongsTo' => ['Things']
]);

#VideosController
$video = $this->Videos
	->find('translations')
	->contain(['Things'])
	->firstOrFail();
```

1. In `_addFieldsToQuery`, the ``$query->select($query->repository()->schema()->columns());`` part is wiping out my `Things`. This happens with/without any of my changes applied.

2. `_translations` is always empty on the `Entity` which means you can't do things like ``$video->translation('fr')->title;``. I tried debugging this but can't track it down. Again, this one is with/without my changes.

3. In my commit I'm saving both the translationTable alias and its registryAlias, so when you need those it's in the config. As far as I can tell, the way I have it works, but I'm just making sure I understand what you had in mind for `config['alias']`. Is that supposed to be the translationTable alias? I changed it to wait for `parent::__construct` so your class knows the actual `translationTable`, and take it from that. I also updated your `config['translationTable']` default to be in the format of a `Table` instead of the old-style actual DB table.

At the end of the day I like this method way more than EAV, since each field can be its own type and should use way less `SELECTS`.

**Comment by AD7six** [comment]
Yeah.. that's looking like some cascading confusion/ambiguity from the way things worked before I ~~borked~~ fixed the registry in the core.

> Is that supposed to be the translationTable alias?

yes.

In principle, `$config['translationTable']` (as it was) is unnecessary, It's only really used [here](https://github.com/AD7six/cakephp-shadow-translate/blob/master/src/Model/Behavior/ShadowTranslateBehavior.php#L417) - users should probably just use the registry-alias key. I've got no problem removing/renaming things if it helpful to do so; originally the config was identical [to the core behavior](https://github.com/cakephp/cakephp/blob/3.0/src/ORM/Behavior/TranslateBehavior.php#L72-L80) - but of course, that's insufficient when there are multiple tables for translated content. I don't imagine calling the parent to help there - maybe I'm misreading the diff though.

Will see about creating a test with the missing data you speak of, I haven't noticed what you mention.

**Comment by patrickconroy** [comment]
Thanks for looking at this stuff. The reason the parent is involved is that the parent's constructor sets the actual translationTable which means less guessing in your class as to who's doing the translating. I guess maybe it's overkill to need those aliases in the config since the translationTable is always available? Let me know if you want me to remove those and just call those in the methods who need them.

**Comment by patrickconroy** [comment]
Hey @AD7six I wrote a failing test, https://github.com/patrickconroy/cakephp-shadow-translate/commit/456732f0e90983d9c19d1595ac30b985af8d2fe1, `ShadowTranslateBehaviorTest ::testAssociations`. You can see that that find wipes out the `Author` on the `Articles` entity since your `_addFieldsToQuery` is updating the select clause and removing the associated fields.
